[build]
  command = "npm install && npm start"
  publish = "."
  functions = "functions"

[build.environment]
  NODE_VERSION = "18"

[[redirects]]
  from = "/*"
  to = "/.netlify/functions/server"
  status = 200
